name: "Hello World Workflow"

on:
 push:
   branches:
       -master 
       -production

jobs:
  hello_world:
      runs_on: ubuntu-latest
      steps:
          -name: "Print Hello World"
          run: echo "Hello CI/CD World"
